<?php

namespace RM_PagBank\Test\Connect\Payments;

use RM_PagBank\Connect\Payments\CreditCard;
use WC_Helper_Order;

class CreditCardTest extends \WP_UnitTestCase
{

	public function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function testPrepare()
    {
		$order = WC_Helper_Order::create_order();
		$order->set_total(100);


    }
}
