name: Build

on:
  push:
    branches:
      - '**'  # Aciona em todos os branches
    tags:
      - '**'  # Aciona em todas as tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build